services:
  db:
    image: postgres:18
    restart: always
    volumes:
      - ./db-data17:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    env_file:
      - db.env

  clh:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    env_file:
      clh.env
    ports:
      - "8088:8088"
    command: ["/app/clh-server"]

  test:
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    links:
      - db
    env_file:
      clh.env
    command: ["bash", "-c", "/app/setup-db.sh && cargo test -- --no-capture"]
